# Generated by Django 4.1.2 on 2022-10-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_telegramuser_full_name_telegramuser_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='users_name',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='Telegram id'),
        ),
    ]
