# Generated by Django 4.1.2 on 2022-11-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_telegramuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram id'),
        ),
    ]
