# Generated by Django 4.1.2 on 2022-11-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='comname',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='inn',
        ),
    ]
